# Generated by Django 5.1.3 on 2024-12-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_ecommerceusers_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommerceusers',
            name='user_image',
            field=models.FileField(upload_to='documents'),
        ),
    ]
